/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.assertNotNull

class AppTest {

}


/**
 token jwt assinado com HMAC256
 eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c

 token jwt assinato com RS256
 eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyXzEyMzQiLCJlbWFpbCI6InVzdWFyaW9AZXhlbXBsby5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTcxMjM0NTYsImV4cCI6MTcxNzIwOTg1Nn0.VGhpcyBpcyBqdXN0IGFuIGV4YW1wbGUgc2lnbmF0dXJlLiBJbiBhIHJlYWwgc2NlbmFyaW8sIHRoaXMgd291bGQgYmUgYSB2YWxpZCBSU0Egc2lnbmF0dXJlIGdlbmVyYXRlZCB1c2luZyBhIHByaXZhdGUga2V5Lg==

 */